---
name: Update Coverage
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - name: Download dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: go test ./...

      - name: Run test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          PATH="${PATH}:$(go env GOPATH)/bin"
          GO111MODULE=off go get -u github.com/mattn/goveralls
          goveralls -service=github
